name: Run Tests for IPs
on: [push]
jobs:
  Prepare-IPs-Matrix:
    runs-on: ubuntu-latest
    outputs:
      IPs: ${{ steps.set-IPs-matrix.outputs.IPs }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set IPs Matrix
        id: set-IPs-matrix
        run: |
          python3 ./.github/scripts/get_IPs_matrix.py
          echo "IPs=$(python3 ./.github/scripts/get_IPs_matrix.py)" >> "$GITHUB_OUTPUT"
  IPs:
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.Prepare-IPs-Matrix.outputs.IPs) }}
    needs: [Prepare-IPs-Matrix]
    name: ${{ matrix.IPs.name }}
    uses: ./.github/workflows/run_IP.yaml
    with:
      url: ${{ matrix.IPs.url }}
      test-names: "${{ matrix.IPs.test-names }}"
      name: ${{ matrix.IPs.name }}
      buses: ${{ matrix.IPs.buses }}
